import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './editing.css';
import './branding.css';
import './machine.css';
import './printing.css';
import './context-menu.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
